# Generated by Django 5.0 on 2025-04-27 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
