# Generated by Django 5.0 on 2025-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_channel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_identifier',
            field=models.CharField(default='xxx', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
