# Generated by Django 5.0 on 2025-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_channel_channel_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='combine_notifications',
            field=models.BooleanField(default=False, help_text='Combine multiple notifications into a single message'),
        ),
    ]
