# Generated by Django 3.2.9 on 2022-01-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_exchange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coin',
            new_name='Market',
        ),
    ]
