# Generated by Django 3.2.9 on 2022-01-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='market',
            field=models.CharField(choices=[('toman', 'toman'), ('tether', 'tether')], max_length=10, null=True),
        ),
    ]
