# Generated by Django 3.2.9 on 2022-01-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_transaction_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(choices=[('wallex', 'wallex'), ('bitpin', 'bitpin')], max_length=100),
        ),
    ]
