# Generated by Django 3.2.9 on 2022-01-15 00:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_exchange_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
