# Generated by Django 3.2.9 on 2022-01-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='jdate',
        ),
    ]
