# Generated by Django 5.0 on 2023-12-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_rename_date_transaction_jdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='market',
            field=models.CharField(choices=[('irt', 'irt'), ('usdt', 'usdt')], max_length=10, null=True),
        ),
    ]
