# Generated by Django 5.0 on 2023-12-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_transaction_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
