# Generated by Django 5.0 on 2023-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_importer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='platform_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
