# Generated by Django 5.0 on 2023-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_transaction_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
