# Generated by Django 5.0 on 2023-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_importer_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='market',
            field=models.CharField(blank=True, choices=[('irt', 'irt'), ('usdt', 'usdt')], max_length=10, null=True),
        ),
    ]
