# Generated by Django 5.0 on 2023-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_alter_transaction_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market',
            field=models.CharField(blank=True, choices=[('irt', 'irt'), ('usdt', 'usdt')], max_length=10, null=True),
        ),
    ]
