# Generated by Django 5.0 on 2024-01-13 16:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_alter_coin_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='jdate',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
