# Generated by Django 5.0 on 2025-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_alter_transaction_jdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='coin_logos/'),
        ),
    ]
