# Generated by Django 5.0 on 2025-05-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_coin_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='logo',
        ),
    ]
