# Generated by Django 5.0 on 2025-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_remove_coin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='coin_logos/'),
        ),
    ]
