# Generated by Django 5.0 on 2025-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0022_coin_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon_background_color',
            field=models.CharField(blank=True, help_text='Background color for SVG icons in hex format (e.g. #FFFFFF)', max_length=20, null=True),
        ),
    ]
