# Generated by Django 5.0 on 2025-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_coin_icon_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon_png',
            field=models.FileField(blank=True, help_text='PNG icon for the coin', null=True, upload_to='coin_logos/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG icon for the coin', null=True, upload_to='coin_logos/'),
        ),
    ]
