# Generated by Django 5.0 on 2025-05-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_coin_icon_png_alter_coin_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
