# Generated by Django 5.0 on 2023-12-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='market',
            field=models.CharField(choices=[('toman', 'toman'), ('tether', 'tether')], max_length=10, null=True),
        ),
    ]
