# Generated by Django 5.0 on 2023-12-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
