# Generated by Django 5.0 on 2023-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='interval',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='in minutes', null=True),
        ),
    ]
