# Generated by Django 5.0 on 2023-12-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_transaction_change'),
        ('notification', '0006_notification_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exchange.transaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exchange.coin'),
        ),
    ]
