# Generated by Django 5.0 on 2023-12-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notification_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
