# Generated by Django 5.0 on 2025-04-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_notification_market'),
        ('user', '0003_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.channel'),
        ),
    ]
